<?php
    $GLOBALS['DB_SERVER'] = "localhost";
    $GLOBALS['DB_USER'] = "REDACTED";
    $GLOBALS['DB_PASSWORD'] = "REDACTED";
    $GLOBALS['DB_DATABASE_NAME'] = "REDACTED";
    
    $GLOBALS['DEFAULT_START_CASH'] = 2000;
    $GLOBALS['DEFAULT_START_LOAN'] = 5000;
    $GLOBALS['DEFAULT_ITEM_SLOTS'] = 100;
    $GLOBALS['DEFAULT_START_LOCATION'] = "Caladan";
    
    $GLOBALS['LOAN_INTEREST_RATE'] = 0.11;
    
    $GLOBALS['CHANCE_OF_SPICE_EVENT'] = 20;   
    $GLOBALS['CHANCE_TO_RUN'] = 75;  
    $GLOBALS['CHANCE_WIN_FIGHT'] = 25;  
  
?>